version: '3'

services:
  ssh-server1:
    image: alpine
    command: sh -c "apk add --update openssh-server && /usr/sbin/sshd -D"
    ports:
      - "2222:22"
    volumes:
      - ./ssh-server1:/root/.ssh

  ssh-server2:
    image: alpine
    command: sh -c "apk add --update openssh-server && /usr/sbin/sshd -D"
    ports:
      - "2223:22"
    volumes:
      - ./ssh-server2:/root/.ssh
    depends_on:
      - ssh-server1
